#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
    ENABLE=$(uci get fancontrol.settings.enable)
    if [ "$ENABLE" -eq "1" ]; then
        . /etc/config/fancontrol
        /path/to/fan_control.sh &
    fi
}

stop() {
    killall fan_control.sh
}
